-- SQL INSERT cho cong_thuc_chia_se
-- 176 ảnh Món nước — xóa data cũ trước khi import

DELETE FROM cong_thuc_chia_se;

INSERT INTO cong_thuc_chia_se (name, short_name, category, image_url, ingredients, sort_order, active)
VALUES
('Bản sao của áp pồ', 'Bản sao của áp pồ', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/Bản sao của áp pồ copy.webp', '[]', 0, true),
('Cafe đào vàng đá xay', 'Cafe đào vàng đá xay', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/Cafe đào vàng đá xay copy.webp', '[]', 1, true),
('Hồng bì lê tuyết', 'Hồng bì lê tuyết', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/Hồng bì lê tuyết copy.webp', '[]', 2, true),
('Hồng bì nhiệt đới', 'Hồng bì nhiệt đới', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/Hồng bì nhiệt đới copy.webp', '[]', 3, true),
('Latte khoai lang tím', 'Latte khoai lang tím', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/Latte khoai lang tím copy.webp', '[]', 4, true),
('Trà Sữa Khoai môn nghiền', 'Trà Sữa Khoai môn nghiền', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/Trà Sữa Khoai môn nghiền copy.webp', '[]', 5, true),
('Bay trên mùa vàng', 'Bay trên mùa vàng', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/bay trên mùa vàng copy.webp', '[]', 6, true),
('Cacao sữa', 'Cacao sữa', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/cacao sữa copy.webp', '[]', 7, true),
('Cafe hồng bì', 'Cafe hồng bì', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/cafe hồng bì copy.webp', '[]', 8, true),
('Cafe soda dứa ổi', 'Cafe soda dứa ổi', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/cafe soda dứa ổi copy.webp', '[]', 9, true),
('Cafe sầu riêng', 'Cafe sầu riêng', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/cafe sầu riêng copy.webp', '[]', 10, true),
('Cafe sữa dừa', 'Cafe sữa dừa', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/cafe sữa dừa copy.webp', '[]', 11, true),
('Cafe yuzu', 'Cafe yuzu', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/cafe yuzu copy.webp', '[]', 12, true),
('Cam vàng lắc cùng', 'Cam vàng lắc cùng', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/cam vàng lắc cùng copy.webp', '[]', 13, true),
('Cold brew lê', 'Cold brew lê', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/cold brew lê copy.webp', '[]', 14, true),
('Cold brew me', 'Cold brew me', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/cold brew me copy.webp', '[]', 15, true),
('Cold brew quýt', 'Cold brew quýt', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/cold brew quýt copy.webp', '[]', 16, true),
('Cung hỷ phát tài', 'Cung hỷ phát tài', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/cung hỷ phát tài copy.webp', '[]', 17, true),
('Cốt long tỉnh chi xuân', 'Cốt long tỉnh chi xuân', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/cốt long tỉnh chi xuân copy.webp', '[]', 18, true),
('Dahongpao', 'Dahongpao', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/dahongpao copy.webp', '[]', 19, true),
('Dâu tây thanh mai', 'Dâu tây thanh mai', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/dâu tây thanh mai copy.webp', '[]', 20, true),
('Dâu tây thanh mai đá xay', 'Dâu tây thanh mai đá xay', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/dâu tây thanh mai đá xay copy.webp', '[]', 21, true),
('Dâu tằm dâu tây', 'Dâu tằm dâu tây', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/dâu tằm dâu tây copy.webp', '[]', 22, true),
('Hoa hồng nho xanh', 'Hoa hồng nho xanh', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/hoa hồng nho xanh copy.webp', '[]', 23, true),
('Hoa nhai thanh mai', 'Hoa nhai thanh mai', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/hoa nhai thanh mai copy.webp', '[]', 24, true),
('Hoa quả nhiệt đới', 'Hoa quả nhiệt đới', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/hoa quả nhiệt đới copy.webp', '[]', 25, true),
('Hà hoa mạn', 'Hà hoa mạn', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/hà hoa mạn copy.webp', '[]', 26, true),
('Hà hoa mận', 'Hà hoa mận', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/hà hoa mận copy.webp', '[]', 27, true),
('Hòa dâu mận', 'Hòa dâu mận', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/hòa dâu mận copy.webp', '[]', 28, true),
('Hồng bì cam quế', 'Hồng bì cam quế', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/hồng bì cam quế copy.webp', '[]', 29, true),
('Hồng bì kem tuyết', 'Hồng bì kem tuyết', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/hồng bì kem tuyết copy.webp', '[]', 30, true),
('Hồng bì si mơ (2)', 'Hồng bì si mơ (2)', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/hồng bì si mơ (2) copy.webp', '[]', 31, true),
('Hồng bì đá xay', 'Hồng bì đá xay', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/hồng bì đá xay copy.webp', '[]', 32, true),
('Hồng lựu vương vấn', 'Hồng lựu vương vấn', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/hồng lựu vương vấn copy.webp', '[]', 33, true),
('Hồng nhan thanh mai', 'Hồng nhan thanh mai', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/hồng nhan thanh mai copy.webp', '[]', 34, true),
('Hồng nho thanh lương', 'Hồng nho thanh lương', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/hồng nho thanh lương copy.webp', '[]', 35, true),
('Hồng trà shan tuyết', 'Hồng trà shan tuyết', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/hồng trà shan tuyết copy.webp', '[]', 36, true),
('Hồng trà shan tuyết version 2', 'Hồng trà shan tuyết version 2', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/hồng trà shan tuyết version 2 copy.webp', '[]', 37, true),
('Hồng trà sài gòn', 'Hồng trà sài gòn', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/hồng trà sài gòn copy.webp', '[]', 38, true),
('Hồng trà đào', 'Hồng trà đào', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/hồng trà đào copy.webp', '[]', 39, true),
('Kim ngọc kỳ duyên', 'Kim ngọc kỳ duyên', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/kim ngọc kỳ duyên copy.webp', '[]', 40, true),
('Kombucha chanh leo', 'Kombucha chanh leo', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/kombucha chanh leo copy.webp', '[]', 41, true),
('Kombucha dâu tằm ', 'Kombucha dâu tằm ', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/kombucha dâu tằm  copy.webp', '[]', 42, true),
('Kombucha kumquat', 'Kombucha kumquat', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/kombucha kumquat copy.webp', '[]', 43, true),
('Kombucha lựu', 'Kombucha lựu', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/kombucha lựu copy.webp', '[]', 44, true),
('Kombucha yuzu', 'Kombucha yuzu', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/kombucha yuzu copy.webp', '[]', 45, true),
('Kumquat đá xay', 'Kumquat đá xay', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/kumquat đá xay copy.webp', '[]', 46, true),
('Kumquat đá xay version 2', 'Kumquat đá xay version 2', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/kumquat đá xay version 2.webp', '[]', 47, true),
('Latte cafe dâu', 'Latte cafe dâu', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/latte cafe dâu copy.webp', '[]', 48, true),
('Long nhãn tuyết sơn (2)', 'Long nhãn tuyết sơn (2)', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/long nhãn tuyết sơn (2) copy.webp', '[]', 49, true),
('Long tỉnh kem cheese', 'Long tỉnh kem cheese', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/long tỉnh kem cheese copy.webp', '[]', 50, true),
('Long tỉnh kem cheese cốm', 'Long tỉnh kem cheese cốm', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/long tỉnh kem cheese cốm copy.webp', '[]', 51, true),
('Lê dừa hương sắc', 'Lê dừa hương sắc', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/lê dừa hương sắc copy.webp', '[]', 52, true),
('Lê quýt', 'Lê quýt', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/lê quýt copy.webp', '[]', 53, true),
('Lê quế hoa (2)', 'Lê quế hoa (2)', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/lê quế hoa (2) copy.webp', '[]', 54, true),
('Lệ chi hồng thanh', 'Lệ chi hồng thanh', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/lệ chi hồng thanh copy.webp', '[]', 55, true),
('Lệ chi mộc tê', 'Lệ chi mộc tê', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/lệ chi mộc tê copy.webp', '[]', 56, true),
('Lực ngọc thiên hương', 'Lực ngọc thiên hương', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/lực ngọc thiên hương copy.webp', '[]', 57, true),
('Mango coco', 'Mango coco', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/mango coco copy.webp', '[]', 58, true),
('Matcha dâu', 'Matcha dâu', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/matcha dâu copy.webp', '[]', 59, true),
('Matcha latte amo', 'Matcha latte amo', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/matcha latte amo copy.webp', '[]', 60, true),
('Matcha lermao', 'Matcha lermao', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/matcha lermao copy.webp', '[]', 61, true),
('Matcha mochi nóng', 'Matcha mochi nóng', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/matcha mochi nóng copy.webp', '[]', 62, true),
('Mò eme', 'Mò eme', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/mò eme copy.webp', '[]', 63, true),
('Mơ má đào', 'Mơ má đào', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/mơ má đào copy.webp', '[]', 64, true),
('Mạn thơm', 'Mạn thơm', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/mạn thơm copy.webp', '[]', 65, true),
('Mạn tám đàn đông', 'Mạn tám đàn đông', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/mạn tám đàn đông copy.webp', '[]', 66, true),
('Ngọc hồng châu', 'Ngọc hồng châu', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/ngọc hồng châu copy.webp', '[]', 67, true),
('Nhai thanh vũ', 'Nhai thanh vũ', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/nhai thanh vũ copy.webp', '[]', 68, true),
('Nho nhỏ', 'Nho nhỏ', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/nho nhỏ copy.webp', '[]', 69, true),
('Nho đào cam vàng', 'Nho đào cam vàng', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/nho đào cam vàng copy.webp', '[]', 70, true),
('Nhài chanh đón hạ', 'Nhài chanh đón hạ', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/nhài chanh đón hạ copy.webp', '[]', 71, true),
('Nhài thanh vũ version 2', 'Nhài thanh vũ version 2', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/nhài thanh vũ version 2.webp', '[]', 72, true),
('Nhài ẩn trong quýt', 'Nhài ẩn trong quýt', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/nhài ẩn trong quýt copy.webp', '[]', 73, true),
('Nhãn dừa', 'Nhãn dừa', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/nhãn dừa copy.webp', '[]', 74, true),
('Nhãn dừa nhiệt đới', 'Nhãn dừa nhiệt đới', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/nhãn dừa nhiệt đới copy.webp', '[]', 75, true),
('Nhãn dừa đá xay', 'Nhãn dừa đá xay', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/nhãn dừa đá xay copy.webp', '[]', 76, true),
('Nhãn hồng nhan', 'Nhãn hồng nhan', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/nhãn hồng nhan copy.webp', '[]', 77, true),
('Nước dừa nhãn hoa', 'Nước dừa nhãn hoa', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/nước dừa nhãn hoa copy.webp', '[]', 78, true),
('Oolong sữa tứ quý', 'Oolong sữa tứ quý', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/oolong sữa tứ quý copy.webp', '[]', 79, true),
('Quýt ẩn nhài', 'Quýt ẩn nhài', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/quýt ẩn nhài copy.webp', '[]', 80, true),
('Shan dứa', 'Shan dứa', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/shan dứa copy.webp', '[]', 81, true),
('Shan tuyết mơ mận', 'Shan tuyết mơ mận', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/shan tuyết mơ mận copy.webp', '[]', 82, true),
('Sinh dã dừa', 'Sinh dã dừa', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/sinh dã dừa copy.webp', '[]', 83, true),
('Sinh dã dừa version 2', 'Sinh dã dừa version 2', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/sinh dã dừa version 2 copy.webp', '[]', 84, true),
('Sữa chua dâu tằm', 'Sữa chua dâu tằm', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/sữa chua dâu tằm copy.webp', '[]', 85, true),
('Sữa chua dâu tằm đá xay', 'Sữa chua dâu tằm đá xay', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/sữa chua dâu tằm đá xay copy.webp', '[]', 86, true),
('Sữa chua lắc dâu tằm', 'Sữa chua lắc dâu tằm', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/sữa chua lắc dâu tằm copy.webp', '[]', 87, true),
('Sữa chua việt quất đá xay', 'Sữa chua việt quất đá xay', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/sữa chua việt quất đá xay copy.webp', '[]', 88, true),
('Sữa dừa khoai môn', 'Sữa dừa khoai môn', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/sữa dừa khoai môn copy.webp', '[]', 89, true),
('Thanh đào', 'Thanh đào', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/thanh đào copy.webp', '[]', 90, true),
('Thất lý hương', 'Thất lý hương', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/thất lý hương copy.webp', '[]', 91, true),
('Trà chanh kumquat', 'Trà chanh kumquat', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/trà chanh kumquat copy.webp', '[]', 92, true),
('Trà chanh việt quất', 'Trà chanh việt quất', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/trà chanh việt quất copy.webp', '[]', 93, true),
('Trà chanh đại hồng bào', 'Trà chanh đại hồng bào', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/trà chanh đại hồng bào copy.webp', '[]', 94, true),
('Trà cúc quýt', 'Trà cúc quýt', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/trà cúc quýt copy.webp', '[]', 95, true),
('Trà dừa khôn', 'Trà dừa khôn', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/trà dừa khôn copy.webp', '[]', 96, true),
('Trà dừa lưới', 'Trà dừa lưới', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/trà dừa lưới copy.webp', '[]', 97, true),
('Trà kiều mạch', 'Trà kiều mạch', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/trà kiều mạch copy.webp', '[]', 98, true),
('Trà nho kem cheese', 'Trà nho kem cheese', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/trà nho kem cheese copy.webp', '[]', 99, true),
('Trà nho nhỏ', 'Trà nho nhỏ', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/trà nho nhỏ copy.webp', '[]', 100, true),
('Trà nho ruby', 'Trà nho ruby', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/trà nho ruby copy.webp', '[]', 101, true),
('Trà nho đào', 'Trà nho đào', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/trà nho đào copy.webp', '[]', 102, true),
('Trà quất hồng bì', 'Trà quất hồng bì', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/trà quất hồng bì copy.webp', '[]', 103, true),
('Trà sen kem cheese lá dứa', 'Trà sen kem cheese lá dứa', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/trà sen kem cheese lá dứa copy.webp', '[]', 104, true),
('Trà sữa bộ kiều mạch', 'Trà sữa bộ kiều mạch', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/trà sữa bộ kiều mạch copy.webp', '[]', 105, true),
('Trà sữa cốm', 'Trà sữa cốm', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/trà sữa cốm copy.webp', '[]', 106, true),
('Trà sữa hoa dành dành', 'Trà sữa hoa dành dành', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/trà sữa hoa dành dành copy.webp', '[]', 107, true),
('Trà sữa hoa mộc tê', 'Trà sữa hoa mộc tê', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/trà sữa hoa mộc tê copy.webp', '[]', 108, true),
('Trà sữa hoa sen (2)', 'Trà sữa hoa sen (2)', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/trà sữa hoa sen (2) copy.webp', '[]', 109, true),
('Trà sữa hồng shan tuyết', 'Trà sữa hồng shan tuyết', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/trà sữa hồng shan tuyết copy.webp', '[]', 110, true),
('Trà sữa kiều mạch (2)', 'Trà sữa kiều mạch (2)', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/trà sữa kiều mạch (2) copy.webp', '[]', 111, true),
('Trà sữa kiều mạch', 'Trà sữa kiều mạch', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/trà sữa kiều mạch copy.webp', '[]', 112, true),
('Trà sữa long nhãn', 'Trà sữa long nhãn', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/trà sữa long nhãn copy.webp', '[]', 113, true),
('Trà sữa long tỉnh chi xuân (2)', 'Trà sữa long tỉnh chi xuân (2)', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/trà sữa long tỉnh chi xuân (2) copy.webp', '[]', 114, true),
('Trà sữa long tỉnh chi xuân 2', 'Trà sữa long tỉnh chi xuân 2', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/trà sữa long tỉnh chi xuân 2 copy.webp', '[]', 115, true),
('Trà sữa lê hoa sen', 'Trà sữa lê hoa sen', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/trà sữa lê hoa sen copy.webp', '[]', 116, true),
('Trà sữa nho', 'Trà sữa nho', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/trà sữa nho copy.webp', '[]', 117, true),
('Trà sữa nướng (2)', 'Trà sữa nướng (2)', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/trà sữa nướng (2) copy.webp', '[]', 118, true),
('Trà sữa phong lan (2)', 'Trà sữa phong lan (2)', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/trà sữa phong lan (2) copy.webp', '[]', 119, true),
('Trà sữa quế hoa (2)', 'Trà sữa quế hoa (2)', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/trà sữa quế hoa (2) copy.webp', '[]', 120, true),
('Trà sữa quế hoa khoa môn (2)', 'Trà sữa quế hoa khoa môn (2)', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/trà sữa quế hoa khoa môn (2) copy.webp', '[]', 121, true),
('Trà sữa quế hoa version 2', 'Trà sữa quế hoa version 2', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/trà sữa quế hoa version 2 copy.webp', '[]', 122, true),
('Trà sữa quế hoa version 2', 'Trà sữa quế hoa version 2', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/trà sữa quế hoa version 2.webp', '[]', 123, true),
('Trà sữa shan tuyết (2)', 'Trà sữa shan tuyết (2)', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/trà sữa shan tuyết (2) copy.webp', '[]', 124, true),
('Trà sữa shan tuyết (3)', 'Trà sữa shan tuyết (3)', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/trà sữa shan tuyết (3) copy.webp', '[]', 125, true),
('Trà sữa sài gòn (2)', 'Trà sữa sài gòn (2)', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/trà sữa sài gòn (2) copy.webp', '[]', 126, true),
('Trà sữa sài gòn version 2', 'Trà sữa sài gòn version 2', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/trà sữa sài gòn version 2.webp', '[]', 127, true),
('Trà sữa thiết quan âm (2)', 'Trà sữa thiết quan âm (2)', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/trà sữa thiết quan âm (2) copy.webp', '[]', 128, true),
('Trà sữa thiết quan âm (3)', 'Trà sữa thiết quan âm (3)', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/trà sữa thiết quan âm (3) copy.webp', '[]', 129, true),
('Trà sữa ô long đào', 'Trà sữa ô long đào', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/trà sữa ô long đào copy.webp', '[]', 130, true),
('Trà sữa ô long đậm vị', 'Trà sữa ô long đậm vị', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/trà sữa ô long đậm vị copy.webp', '[]', 131, true),
('Trà sữa đào', 'Trà sữa đào', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/trà sữa đào copy.webp', '[]', 132, true),
('Trà sữa đào version 2', 'Trà sữa đào version 2', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/trà sữa đào version 2 copy.webp', '[]', 133, true),
('Trà sữa đại hồng bào (2)', 'Trà sữa đại hồng bào (2)', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/trà sữa đại hồng bào (2) copy.webp', '[]', 134, true),
('Trà táo chanh leo', 'Trà táo chanh leo', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/trà táo chanh leo copy.webp', '[]', 135, true),
('Trà vải hoa hồng', 'Trà vải hoa hồng', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/trà vải hoa hồng copy.webp', '[]', 136, true),
('Trà xanh nhài', 'Trà xanh nhài', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/trà xanh nhài copy.webp', '[]', 137, true),
('Trà xoài chanh dây', 'Trà xoài chanh dây', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/trà xoài chanh dây copy.webp', '[]', 138, true),
('Trà xoài chanh leo', 'Trà xoài chanh leo', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/trà xoài chanh leo copy.webp', '[]', 139, true),
('Trà xoài dừa', 'Trà xoài dừa', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/trà xoài dừa copy.webp', '[]', 140, true),
('Trà xoài quýt', 'Trà xoài quýt', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/trà xoài quýt copy.webp', '[]', 141, true),
('Trà ô long hoa sen', 'Trà ô long hoa sen', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/trà ô long hoa sen copy.webp', '[]', 142, true),
('Trà ô long đào', 'Trà ô long đào', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/trà ô long đào copy.webp', '[]', 143, true),
('Trà đào cam sả', 'Trà đào cam sả', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/trà đào cam sả copy.webp', '[]', 144, true),
('Trà đào cam sả version 2', 'Trà đào cam sả version 2', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/trà đào cam sả version 2 copy.webp', '[]', 145, true),
('Trà đào cam xoài', 'Trà đào cam xoài', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/trà đào cam xoài copy.webp', '[]', 146, true),
('Trà đào chanh sả', 'Trà đào chanh sả', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/trà đào chanh sả copy.webp', '[]', 147, true),
('Trà đào nho', 'Trà đào nho', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/trà đào nho copy.webp', '[]', 148, true),
('Trà đào nho version 2', 'Trà đào nho version 2', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/trà đào nho version 2 copy.webp', '[]', 149, true),
('Trà đào sữa', 'Trà đào sữa', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/trà đào sữa copy.webp', '[]', 150, true),
('Trà đào xí muội', 'Trà đào xí muội', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/trà đào xí muội copy.webp', '[]', 151, true),
('Trà ổi hồng', 'Trà ổi hồng', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/trà ổi hồng copy.webp', '[]', 152, true),
('Tâm hoa lý', 'Tâm hoa lý', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/tâm hoa lý copy.webp', '[]', 153, true),
('Túy lựu đào hoa', 'Túy lựu đào hoa', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/túy lựu đào hoa copy.webp', '[]', 154, true),
('Vũ hồi ma hei', 'Vũ hồi ma hei', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/vũ hồi ma hei copy.webp', '[]', 155, true),
('Vải chanh leo', 'Vải chanh leo', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/vải chanh leo copy.webp', '[]', 156, true),
('Vải hoa hồng', 'Vải hoa hồng', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/vải hoa hồng copy.webp', '[]', 157, true),
('Vải đong hương táo', 'Vải đong hương táo', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/vải đong hương táo copy.webp', '[]', 158, true),
('Xoài chanh leo', 'Xoài chanh leo', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/xoài chanh leo copy.webp', '[]', 159, true),
('Xoài sữa dừa', 'Xoài sữa dừa', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/xoài sữa dừa copy.webp', '[]', 160, true),
('Yakult việt quất', 'Yakult việt quất', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/yakult việt quất copy.webp', '[]', 161, true),
('Yuzu chanh quất', 'Yuzu chanh quất', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/yuzu chanh quất copy.webp', '[]', 162, true),
('Yuzu shan version 2', 'Yuzu shan version 2', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/yuzu shan version 2 copy.webp', '[]', 163, true),
('ánh mặt trời', 'ánh mặt trời', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/ánh mặt trời copy.webp', '[]', 164, true),
('ô long hoa sen', 'ô long hoa sen', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/ô long hoa sen copy.webp', '[]', 165, true),
('ô long lựu tứ quý', 'ô long lựu tứ quý', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/ô long lựu tứ quý copy.webp', '[]', 166, true),
('ô long shan tuyết dứa', 'ô long shan tuyết dứa', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/ô long shan tuyết dứa copy.webp', '[]', 167, true),
('ô long shan tuyểt', 'ô long shan tuyểt', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/ô long shan tuyểt copy.webp', '[]', 168, true),
('đào vàng chanh dây', 'đào vàng chanh dây', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/đào vàng chanh dây copy.webp', '[]', 169, true),
('đào vàng chanh sả', 'đào vàng chanh sả', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/đào vàng chanh sả copy.webp', '[]', 170, true),
('ổi hồng dâu tây (2)', 'ổi hồng dâu tây (2)', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/ổi hồng dâu tây (2) copy.webp', '[]', 171, true),
('ổi hồng dâu tây version 2', 'ổi hồng dâu tây version 2', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/ổi hồng dâu tây version 2 copy.webp', '[]', 172, true),
('ổi hồng dâu tây version 2', 'ổi hồng dâu tây version 2', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/ổi hồng dâu tây version 2.webp', '[]', 173, true),
('ổi hồng dâu tây ô long sen', 'ổi hồng dâu tây ô long sen', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/ổi hồng dâu tây ô long sen copy.webp', '[]', 174, true),
('ổi hồng xí muội', 'ổi hồng xí muội', 'Món nước', '/images/gallery/Cong-thuc-mien-phi/mon-nuoc/ổi hồng xí muội copy.webp', '[]', 175, true)
ON CONFLICT DO NOTHING;
